set_property SRC_FILE_INFO {cfile:/home/seba/Workspace/aliexpress_kintex325/hdmi/fpga.xdc rfile:../../../../fpga.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AB11 IOSTANDARD DIFF_SSTL15} [get_ports clk_200mhz_p]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AC11 IOSTANDARD DIFF_SSTL15} [get_ports clk_200mhz_n]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC C24 IOSTANDARD LVCMOS33} [get_ports btn3]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AA2 IOSTANDARD LVCMOS15} [get_ports {leds[0]}]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AD5 IOSTANDARD LVCMOS15} [get_ports {leds[1]}]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC W10 IOSTANDARD LVCMOS15} [get_ports {leds[2]}]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC Y10 IOSTANDARD LVCMOS15} [get_ports {leds[3]}]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AE10 IOSTANDARD LVCMOS15} [get_ports {leds[4]}]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC W11 IOSTANDARD LVCMOS15} [get_ports {leds[5]}]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC V11 IOSTANDARD LVCMOS15} [get_ports {leds[6]}]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC Y12 IOSTANDARD LVCMOS15} [get_ports {leds[7]}]
set_property src_info {type:XDC file:1 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC P21 IOSTANDARD TMDS_33} [get_ports {hdmi_clk[0]}] ;#n
set_property src_info {type:XDC file:1 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC R21 IOSTANDARD TMDS_33} [get_ports {hdmi_clk[1]}] ;#p
set_property src_info {type:XDC file:1 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC M19 IOSTANDARD TMDS_33} [get_ports {hdmi_d0[0]}]
set_property src_info {type:XDC file:1 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC N18 IOSTANDARD TMDS_33} [get_ports {hdmi_d0[1]}]
set_property src_info {type:XDC file:1 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC M22 IOSTANDARD TMDS_33} [get_ports {hdmi_d1[0]}]
set_property src_info {type:XDC file:1 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC M21 IOSTANDARD TMDS_33} [get_ports {hdmi_d1[1]}]
set_property src_info {type:XDC file:1 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC K26 IOSTANDARD TMDS_33} [get_ports {hdmi_d2[0]}]
set_property src_info {type:XDC file:1 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC K25 IOSTANDARD TMDS_33} [get_ports {hdmi_d2[1]}]
set_property src_info {type:XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC M26 IOSTANDARD LVCMOS33} [get_ports hdmi_cec]
set_property src_info {type:XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC N26 IOSTANDARD LVCMOS33} [get_ports hdmi_hdp]
set_property src_info {type:XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC K21 IOSTANDARD LVCMOS33} [get_ports hdmi_scl]
set_property src_info {type:XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC L23 IOSTANDARD LVCMOS33} [get_ports hdmi_sda]
